export default [
  {
    id: 1,
    title: "Poco X3",
    price: 20000,
    properties: {
      color: "Red",
      rom: "128gb",
      ram: "6gb",
    },
    img: "https://i01.appmifile.com/webfile/globalimg/products/pc/poco-x3-nfc/specs-header.png",
    quantity: 1,
  },
  {
    id: 2,
    title: "Poco m3",
    price: 16000,
    properties: {
      color: "Yellow",
      rom: "128gb",
      ram: "4gb",
    },
    img: "https://freebiescloud.com/wp-content/uploads/2020/11/5.png",
    quantity: 1,
  },
  {
    id: 3,
    title: "Redmi Note 10",
    price: 23000,
    properties: {
      color: "Black",
      rom: "128gb",
      ram: "8gb",
    },
    img: "https://th.bing.com/th/id/R.d8cee78f00e1d5ef9cdea49c1b7a8af1?rik=2kKtZ%2bSRf2CxoQ&pid=ImgRaw&r=0",
    quantity: 1,
  },
  {
    id: 4,
    title: "samsung s23 ultra",
    price: 120000,
    properties: {
      color: "Silver",
      rom: "256gb",
      ram: "8gb",
    },
    img: "https://freebiescloud.com/wp-content/uploads/2020/11/5.png",
    quantity: 1,
  },
  {
    id: 5,
    title: "Samsung Galaxy M51",
    price: 90000,
    properties: {
      color: "Blue",
      rom: "256gb",
      ram: "8gb",
    },
    img: "https://freebiescloud.com/wp-content/uploads/2020/11/5.png",
    quantity: 1,
  },
  {
    id: 6,
    title: "Apple Iphone X",
    price: 40000,
    properties: {
      color: "Silver",
      rom: "64gb",
      ram: "2gb",
    },
    img: "https://th.bing.com/th/id/R.d8cee78f00e1d5ef9cdea49c1b7a8af1?rik=2kKtZ%2bSRf2CxoQ&pid=ImgRaw&r=0",
    quantity: 1,
  },
  {
    id: 7,
    title: "Apple Iphone 11",
    price: 11000,
    properties: {
      color: "Black",
      rom: "128gb",
      ram: "6gb",
    },
    img: "https://th.bing.com/th/id/R.d8cee78f00e1d5ef9cdea49c1b7a8af1?rik=2kKtZ%2bSRf2CxoQ&pid=ImgRaw&r=0",
    quantity: 1,
  },
  {
    id: 8,
    title: "Realme c15",
    price: 15000,
    properties: {
      color: "Red",
      rom: "128gb",
      ram: "6gb",
    },
    img: "https://th.bing.com/th/id/R.d8cee78f00e1d5ef9cdea49c1b7a8af1?rik=2kKtZ%2bSRf2CxoQ&pid=ImgRaw&r=0",
    quantity: 1,
  },
];
