export default [
  {
    id: 1,
    title: "Poco X3",
    price: 20000,
    properties: {
      color: "Red",
      rom: "128gb",
      ram: "6gb",
    },
    img: "https://i01.appmifile.com/webfile/globalimg/products/pc/poco-x3-nfc/specs-header.png",
    quantity: 1,
  },
  {
    id: 2,
    title: "Poco m3",
    price: 16000,
    properties: {
      color: "Yellow",
      rom: "128gb",
      ram: "4gb",
    },
    img: "https://www.mrgadget.co.ug/wp-content/uploads/2021/10/poco-m3..jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Redmi Note 10",
    price: 23000,
    properties: {
      color: "Black",
      rom: "128gb",
      ram: "8gb",
    },
    img: "https://www.gizmochina.com/wp-content/uploads/2020/09/1-16-500x500.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "samsung s23 ultra",
    price: 120000,
    properties: {
      color: "Silver",
      rom: "256gb",
      ram: "8gb",
    },
    img: "https://www.excelestore.com.bd/public/uploads/all/dUPPjYAaZ3hklobyHajrLMs1I5LCPAgcNtOmMh2b.webp",
    quantity: 1,
  },
  {
    id: 5,
    title: "Samsung Galaxy M51",
    price: 90000,
    properties: {
      color: "Blue",
      rom: "256gb",
      ram: "8gb",
    },
    img: "https://www.excelestore.com.bd/public/uploads/all/elthMTUhVIu0teYEwxm3tGqpkd4OP5pTj1iyHVdH.webp",
    quantity: 1,
  },
  {
    id: 6,
    title: "Apple Iphone X",
    price: 40000,
    properties: {
      color: "Silver",
      rom: "64gb",
      ram: "2gb",
    },
    img: "https://www.gizmochina.com/wp-content/uploads/2017/09/iPhone-X-Profile-Page-550x550.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Apple Iphone 11",
    price: 11000,
    properties: {
      color: "Black",
      rom: "128gb",
      ram: "6gb",
    },
    img: "https://www.gizmochina.com/wp-content/uploads/2019/09/Apple-iPhone-11-Pro.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "Realme c15",
    price: 15000,
    properties: {
      color: "Red",
      rom: "128gb",
      ram: "6gb",
    },
    img: "https://www.mobilebazar.com.bd/assets/img/Realme-C15-Qualcomm-Edition-Official-image-499x499.webp",
    quantity: 1,
  },
];
